export { default as ContactPage } from './ContactPage'
export { default as CoverPage } from './CoverPage'
export { default as FocusPage } from './FocusPage'
export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as TechPage } from './TechPage'
